package ua.com.skarbmandriv.api;

import org.junit.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'vko' at '1/20/16 9:03 PM' with Gradle 2.7
 *
 * @author vko, @date 1/20/16 9:03 PM
 */
public class ApplicationTest {
    @Test public void testSomeLibraryMethod() {
    }
}
