/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vko' at '1/20/16 9:03 PM' with Gradle 2.7
 *
 * @author vko, @date 1/20/16 9:03 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
